set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bin_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bin_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bin_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bin_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cat[0]}]
set_property PACKAGE_PIN V17 [get_ports {bin_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {bin_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {bin_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {bin_in[3]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN V7 [get_ports {cat[0]}]
set_property PACKAGE_PIN U7 [get_ports {cat[1]}]
set_property PACKAGE_PIN V5 [get_ports {cat[2]}]
set_property PACKAGE_PIN U5 [get_ports {cat[3]}]
set_property PACKAGE_PIN V8 [get_ports {cat[4]}]
set_property PACKAGE_PIN U8 [get_ports {cat[5]}]
set_property PACKAGE_PIN W6 [get_ports {cat[6]}]
set_property PACKAGE_PIN W7 [get_ports {cat[7]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
